name: Full Stack CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      #######################
      # Client Setup & Build
      #######################

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Lint client
        working-directory: client
        run: npm run lint

      - name: Build client
        working-directory: client
        run: npm run build

      #######################
      # Server Setup & Build
      #######################

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Generate Prisma client
        working-directory: server
        run: npx prisma generate

      - name: Build server
        working-directory: server
        run: npm run build

      - name: Run server tests
        working-directory: server
        run: npm test